### PR TITLE
5.3 Support with encryption

### PR DESCRIPTION
**Pull request by trideout**
This patch includes all changes from @majksner as well as encryption from @golonix modified to support  Laravel 5.3

### CODE REVIEW

**Comment by trideout** [comment]
travis fails because it is attempting to test serialization of closures which is not supported. Should this test simply be removed?

**Comment by golonix** [comment]
You're correct. L5.2 supported closures passed as payload, where L5.3 ditched that.
`Queue` class In L5.2:
```
    protected function createPayload($job, $data = '', $queue = null)
    {
        if ($job instanceof Closure) {
            return json_encode($this->createClosurePayload($job, $data));
        }

        if (is_object($job)) {
            return json_encode([
                'job' => 'Illuminate\Queue\CallQueuedHandler@call',
                'data' => ['commandName' => get_class($job), 'command' => serialize(clone $job)],
            ]);
        }

        return json_encode($this->createPlainPayload($job, $data));
    }
```
`Queue` class in L5.3:
```
    protected function createPayload($job, $data = '', $queue = null)
    {
        if (is_object($job)) {
            $payload = json_encode([
                'job' => 'Illuminate\Queue\CallQueuedHandler@call',
                'data' => [
                    'commandName' => get_class($job),
                    'command' => serialize(clone $job),
                ],
            ]);
        } else {
            $payload = json_encode($this->createPlainPayload($job, $data));
        }

        if (JSON_ERROR_NONE !== json_last_error()) {
            throw new InvalidArgumentException('Unable to create payload: '.json_last_error_msg());
        }

        return $payload;
    }
```
I think you can remove this test or implement closure as payload functionality to Iron MQ.
If you're interested, I've decided to fork this repo and maintain it on my own. It has L5.3 support (https://github.com/HydrefLab/iron-queue).

**Comment by mlantz** [comment]
Hey @trideout and @golonix do you guys know Iron Queue well? I'm not knowledgeable of it, any help to bring this up to par, and then move it forward to 5.4 would be greatly appreciated thank you.

**Comment by golonix** [comment]
@mlantz it looks like this package is abandoned. If you need L5.3 support, you can take a look at my updates (https://github.com/HydrefLab/iron-queue). I'm planning to add L5.4 support within few days.

**Pull request merged**
